export const iconOptions = [
  {title: '葉子 leaf', value: 'ri-leaf-line'},
  {title: '愛心脈搏 heart pulse', value: 'ri-heart-pulse-line'},
  {title: '月亮 moon', value: 'ri-moon-line'},
  {title: '幼苗 seedling', value: 'ri-seedling-line'},
  {title: '閃耀 sparkling', value: 'ri-sparkling-line'},
  {title: '閃耀 2 sparkling', value: 'ri-sparkling-2-line'},
  {title: '水滴 drop', value: 'ri-contrast-drop-2-line'},
  {title: '身體掃描 body scan', value: 'ri-body-scan-line'},
  {title: '折線圖 line chart', value: 'ri-line-chart-line'},
  {title: '眼睛 eye', value: 'ri-eye-line'},
  {title: '盾牌勾選 shield check', value: 'ri-shield-check-line'},
  {title: '天平 scales', value: 'ri-scales-3-line'},
  {title: '愛心 heart', value: 'ri-heart-line'},
  {title: '群組 group', value: 'ri-group-line'},
  {title: '女性 women', value: 'ri-women-line'},
  {title: '兒童 child', value: 'ri-child-line'},
  {title: '皮膚 skin', value: 'ri-skin-line'},
  {title: '聚焦 acupuncture', value: 'ri-focus-3-line'},
  {title: '手心愛心 hand heart', value: 'ri-hand-heart-line'},
  {title: '燒瓶 flask', value: 'ri-flask-line'},
  {title: '閃光 flashlight', value: 'ri-flashlight-line'},
  {title: '問號 question', value: 'ri-question-line'},
  {title: '愛心加號 heart add', value: 'ri-heart-add-line'},
  {title: '刷新 refresh', value: 'ri-refresh-line'},
  {title: '開門 door open', value: 'ri-door-open-line'},
  {title: '使用者愛心 user heart', value: 'ri-user-heart-line'},
  {title: '盾牌十字 shield cross', value: 'ri-shield-cross-line'},
  {title: '脈搏 pulse', value: 'ri-pulse-line'},
] as const

export const iconFieldOptions = {
  list: iconOptions,
} as const
