export const homePageSeed = {
  _id: 'homePage',
  _type: 'homePage',
  title: '首頁',
  hero: {
    titleLine1: '以艾醫身',
    titleLine2: '以苜養心',
    subtitle: '在這裡,我們用溫柔的雙手與傳承千年的智慧,\n守護妳與家人的每一刻健康時光',
    ctaText: '立即預約諮詢',
    ctaTarget: 'booking',
    image: {
      _type: 'externalImage',
      url: 'https://static.readdy.ai/image/8d6cf5771052b01e9700d88a6623b6b6/86c1fda8d4a973044d459bcf3069ab1e.png',
      alt: '艾草意象',
    },
  },
  about: {
    title: '關於艾苜中醫',
    englishTitle: 'Amulette Chinese Medical Clinic',
    lead: '您與家人的隨身健康御守',
    description:
      '在繁忙的生活中，艾苜致力於在您身體失衡前便先一步承接。我們懂妳的優雅，更懂您對家人健康的牽掛。走進艾苜，帶走的不只是一帖藥方，而是身心靈被安穩接住的暖光。',
    features: [
      {
        _key: 'about-feature-01',
        title: '「艾」是呵護',
        description: '像月光般溫潤，照料女性生理節律，讓您的優雅源自健康的自然發光。',
      },
      {
        _key: 'about-feature-02',
        title: '「苜」是滋養',
        description: '像大地般深根，為全家人紮穩健康地基，注入源源不絕的生命動能。',
      },
    ],
    ctaText: '關於艾苜中醫診所',
    ctaTarget: 'services',
    image: {
      _type: 'externalImage',
      url: 'https://readdy.ai/api/search-image?query=Elegant%20traditional%20Chinese%20medicine%20clinic%20interior%20with%20warm%20wooden%20shelves%20displaying%20ceramic%20herb%20jars%20and%20dried%20herbs%2C%20soft%20natural%20lighting%20through%20window%2C%20modern%20minimalist%20design%20combined%20with%20traditional%20elements%2C%20peaceful%20and%20professional%20atmosphere%2C%20warm%20earth%20tones%2C%20clean%20aesthetic&width=800&height=1000&seq=about-clinic-002&orientation=portrait',
      alt: '艾苜中醫診所環境',
    },
  },
  services: {
    title: '主治項目',
    description:
      '融合傳統中醫精髓與現代醫學理念，針對各類常見病症提供個人化診療方案，從根本調理體質，守護您與家人的健康。',
    items: [
      {
        _key: 'service-01',
        number: '01',
        icon: 'ri-heart-pulse-line',
        title: '本草・歸元',
        subtitle: '內科體質調理',
        description: '針對呼吸道修復(長新冠)、自律神經失調(失眠焦慮)、消化機能(胃食道逆流)與泌尿系統進行深層淨化與平衡。',
      },
      {
        _key: 'service-02',
        number: '02',
        icon: 'ri-moon-line',
        title: '月・悅・圓',
        subtitle: '全方位婦科',
        description: '涵蓋月經調律、暖宮溫養、備孕生機(結合人工生殖調理)、產後坐月子復元及熟齡更年期自在調理。',
      },
      {
        _key: 'service-03',
        number: '03',
        icon: 'ri-seedling-line',
        title: '小苗・茁壯',
        subtitle: '兒少生長發育',
        description: '專注於開胃健脾、舒敏抗戰(過敏體質)、改善夜尿與提升專注力的聰明開竅方案。',
      },
      {
        _key: 'service-04',
        number: '04',
        icon: 'ri-sparkling-2-line',
        title: '肌膚・煥采',
        subtitle: '中醫美學皮膚科',
        description: '透過內在疏肝活血與外在美顏針,解決青春痘、濕疹蕁麻疹及暗沉斑點,還原肌膚潤白光透。',
      },
      {
        _key: 'service-05',
        number: '05',
        icon: 'ri-contrast-drop-2-line',
        title: '御顏・緊緻',
        subtitle: '艾苜特色療程',
        description: '運用精微針法刺激面部經絡與筋膜層,促進膠原蛋白新生,改善法令紋與輪廓鬆弛,無需手術達到自然拉提效果。',
      },
      {
        _key: 'service-06',
        number: '06',
        icon: 'ri-body-scan-line',
        title: '輕盈・體雕',
        subtitle: '艾苜特色療程',
        description: '透過穴位埋線技術持續刺激經絡,加速脂肪分解與代謝循環,針對局部頑固脂肪進行精準雕塑,打造健康勻稱身形。',
      },
      {
        _key: 'service-07',
        number: '07',
        icon: 'ri-line-chart-line',
        title: '登峰・轉骨',
        subtitle: '艾苜特色療程',
        description: '把握青春期黃金生長期,結合雷射針灸刺激生長板活性,搭配個人化中藥方劑調理脾胃與腎氣,全方位促進骨骼發育與身高增長。',
      },
      {
        _key: 'service-08',
        number: '08',
        icon: 'ri-eye-line',
        title: '明眸・亮視',
        subtitle: '艾苜特色療程',
        description: '針對長時間使用3C產品造成的眼睛疲勞、乾澀與視力模糊,運用眼周特定穴位針灸改善眼部血液循環,有效延緩近視加深。',
      },
    ],
  },
  whyChoose: {
    titleLine1: '為什麼選擇艾苜',
    titleLine2: '守護您的健康',
    paragraphs: [
      '上醫治未病:古籍《黃帝內經》有云,真正的醫術不應止於「挽救」,更在於「預防」。艾苜(Amulette)源自法語的「御守」,如同御守在災厄來臨前擋去風雨。',
      '我們致力於在您身體失衡的初期,便先一步介入調理。讓每一次的診療,都是為您築起一道溫柔而堅實的健康防線。不只治病,更守護您的健康。',
    ],
    ctaText: '立即預約諮詢',
    ctaTarget: 'booking',
    image: {
      _type: 'externalImage',
      url: 'https://readdy.ai/api/search-image?query=Modern%20Chinese%20medicine%20consultation%20room%20with%20professional%20female%20doctor%20and%20patient%20having%20warm%20conversation%2C%20elegant%20minimalist%20interior%20design%20with%20natural%20wood%20elements%20and%20soft%20lighting%2C%20peaceful%20healing%20atmosphere%2C%20contemporary%20medical%20practice%20combined%20with%20traditional%20wisdom&width=800&height=1000&seq=why-choose-new-003&orientation=portrait',
      alt: '艾苜中醫診療情境',
    },
  },
  team: {
    title: '醫師陣容',
    subtitle: '以仁心仁術，守護您與家人的健康',
    description:
      '艾苜中醫診所匯聚三位專業中醫師，各具深厚學術背景與豐富臨床經驗，涵蓋內科、婦科、皮膚科、針灸及中醫美容等多元領域，為每位患者提供最適切的個人化調理方案。',
    doctors: [
      {_key: 'doctor-01', name: '李俊廷 醫師', title: '內科・針灸・自律神經'},
      {_key: 'doctor-02', name: '歐陽汝亭 醫師', title: '皮膚科・婦科・中醫美容'},
      {_key: 'doctor-03', name: '吳雅筠 醫師', title: '婦科・兒科・物理治療'},
    ],
    image: {
      _type: 'externalImage',
      url: 'https://readdy.ai/api/search-image?query=Three%20professional%20Chinese%20medicine%20doctors%20group%20portrait%20in%20white%20medical%20coats%20standing%20together%20in%20a%20modern%20bright%20clinic%20interior%20warm%20natural%20lighting%20elegant%20minimalist%20background%20all%20smiling%20confidently%20high%20quality%20professional%20medical%20team%20photography%20warm%20tones&width=900&height=600&seq=team-group-photo-clinic&orientation=landscape',
      alt: '艾苜中醫診所醫師團隊',
    },
  },
  process: {
    title: '初診流程',
    subtitle: '五個步驟，開啟您的健康守護之旅',
    steps: [
      {
        _key: 'process-01',
        step: '01',
        title: '預約掛號',
        description: '透過電話或LINE預約您方便的時段,我們將為您安排最適合的醫師。',
        image: {
          url: 'https://public.readdy.ai/ai/img_res/2c59c23382098198db178116fb9d6005.jpg',
          alt: '初診流程：預約掛號',
        },
      },
      {
        _key: 'process-02',
        step: '02',
        title: '初診問診',
        description: '醫師將詳細了解您的身體狀況、生活習慣與主要困擾,建立完整的健康檔案。',
        image: {
          url: 'https://public.readdy.ai/ai/img_res/653a687c3ceef43132abfcbb57b539f5.jpg',
          alt: '初診流程：初診問診',
        },
      },
      {
        _key: 'process-03',
        step: '03',
        title: '望聞問切',
        description: '運用中醫四診法,透過望診、聞診、問診、切脈,全面評估您的體質狀態。',
        image: {
          url: 'https://public.readdy.ai/ai/img_res/02087a97916c03491cbb24efc49d7e8a.jpg',
          alt: '初診流程：望聞問切',
        },
      },
      {
        _key: 'process-04',
        step: '04',
        title: '客製療程',
        description: '根據您的體質與需求,量身訂製專屬的治療方案,包含針灸、中藥或其他療法。',
        image: {
          url: 'https://public.readdy.ai/ai/img_res/4b01ece022e110733c94e609a20db7f4.jpg',
          alt: '初診流程：客製療程',
        },
      },
      {
        _key: 'process-05',
        step: '05',
        title: '持續追蹤',
        description: '定期回診追蹤療效,適時調整治療方案,確保您的健康持續改善與維護。',
        image: {
          url: 'https://public.readdy.ai/ai/img_res/ea577b76c56996ef9de90e2eb2ea0150.jpg',
          alt: '初診流程：持續追蹤',
        },
      },
    ],
  },
  booking: {
    title: '預約艾苜',
    subtitle: '選擇您偏好的聯繫方式,立即開始您的健康調理之旅',
    cards: [
      {
        _key: 'booking-01',
        title: '電話預約',
        value: '06 252 0699',
        href: 'tel:062520699',
        buttonText: '立即撥打',
        icon: 'ri-phone-fill',
        buttonTheme: 'brand',
      },
      {
        _key: 'booking-02',
        title: 'LINE 預約',
        value: '@艾苜中醫',
        href: 'https://lin.ee/EeONEJc',
        buttonText: '加入好友',
        icon: 'ri-line-fill',
        buttonTheme: 'line',
      },
    ],
  },
  faq: {
    titleLine1: '常見',
    titleLine2: '問題',
    description: '我們整理了最常被問到的問題，希望能幫助您更了解我們的服務。',
    items: [
      {
        _key: 'faq-01',
        question: '初診可以預約嗎?',
        answer: '本院可接受初診預約,請透過電話或直接到現場預約。切勿使用 Line 商家或 FB 訊息預約,因為訊息較不即時,您想預約的時間可能已額滿,透過直接溝通比較能夠即時敲定您方便的時間。此外,美顏針、減重、備孕與轉骨因為療程評估與治療施作較為耗時,請務必預約。★ 請尊重彼此的時間,初診預約請提前 20 分鐘報到,以便填妥與建立您的個人病歷資料。★ 切勿無故爽約,違者本院將不再受理您的預約事宜。',
      },
      {
        _key: 'faq-02',
        question: 'Line 線上掛號時間?',
        answer: 'Line 線上掛號時間為【本院營業時間】。這是由於本院線上掛號系統與病歷系統連動,因此線上掛號必須在診所電腦主機開著時方可操作。',
      },
      {
        _key: 'faq-03',
        question: '現場掛號時間?',
        answer: '每個診次開診前 10 分鐘即可受理現場掛號。止掛時間為:・內科(每診關診前 15 分鐘)・針灸或需針灸者(每診關診前 30 分鐘)',
      },
      {
        _key: 'faq-04',
        question: '針灸會不會很痛？',
        answer: '多數人感受到的是輕微刺感或痠脹感，醫師也會依您的接受程度調整治療方式。',
      },
    ],
  },
  gallery: {
    images: [
      {
        _key: 'gallery-01',
        image: {
          _type: 'externalImage',
          url: 'https://readdy.ai/api/search-image?query=modern%20traditional%20chinese%20medicine%20clinic%20interior%20warm%20lighting%20wooden%20furniture%20elegant%20reception%20area%20soft%20beige%20tones%20plants%20decoration%20professional%20medical%20environment%20cozy%20atmosphere%20high%20end%20aesthetic&width=800&height=900&seq=gallery_left_main&orientation=portrait',
          alt: '診所空間',
        },
        label: 'Clinic Space',
        labelZh: '診所空間',
      },
      {
        _key: 'gallery-02',
        image: {
          _type: 'externalImage',
          url: 'https://readdy.ai/api/search-image?query=chinese%20medicine%20consultation%20room%20doctor%20patient%20warm%20wooden%20desk%20herbal%20medicine%20bottles%20soft%20natural%20light%20professional%20calm%20atmosphere%20elegant%20interior%20design&width=800&height=440&seq=gallery_right_top&orientation=landscape',
          alt: '診療室',
        },
        label: 'Consultation Room',
        labelZh: '診療室',
      },
      {
        _key: 'gallery-03',
        image: {
          _type: 'externalImage',
          url: 'https://readdy.ai/api/search-image?query=acupuncture%20treatment%20room%20clean%20white%20bed%20soft%20lighting%20relaxing%20spa%20like%20atmosphere%20traditional%20chinese%20medicine%20clinic%20peaceful%20serene%20environment%20warm%20tones&width=800&height=440&seq=gallery_right_bottom&orientation=landscape',
          alt: '治療室',
        },
        label: 'Treatment Room',
        labelZh: '治療室',
      },
    ],
  },
  testimonials: {
    title: '真實見證',
    description: '來自真實患者的治療心得與推薦',
    items: [
      {
        _key: 'testimonial-01',
        name: '林小姐',
        service: '針灸治療',
        content: '李醫師的針灸技術真的很棒,我的肩頸痠痛問題在幾次治療後就有明顯改善。診所環境很舒適,服務也很親切。',
        time: '2個月前',
      },
      {
        _key: 'testimonial-02',
        name: '陳先生',
        service: '失眠調理',
        content: '長期失眠困擾終於解決了!吳醫師開的中藥很溫和,調理幾週後睡眠品質明顯提升,整個人精神都好很多。',
        time: '1個月前',
      },
      {
        _key: 'testimonial-03',
        name: '王媽媽',
        service: '兒童過敏',
        content: '小孩的過敏體質經過歐陽醫師的調理後改善很多,現在很少再有過敏發作的情況,真的很感謝醫師的專業。',
        time: '3週前',
      },
      {
        _key: 'testimonial-04',
        name: '張小姐',
        service: '美顏針',
        content: '美顏針的效果超乎預期!不僅臉部線條更緊實,膚質也變好了。醫師很細心,每次都會詳細說明治療過程。',
        time: '2週前',
      },
      {
        _key: 'testimonial-05',
        name: '劉太太',
        service: '婦科調理',
        content: '更年期的各種不適症狀在這裡得到很好的改善,醫師很有耐心地解釋病情,讓我對治療很有信心。',
        time: '1個月前',
      },
      {
        _key: 'testimonial-06',
        name: '黃先生',
        service: '消化調理',
        content: '胃食道逆流的問題困擾我很久,經過中藥調理後現在已經很少發作了,生活品質提升很多,謝謝醫師!',
        time: '6週前',
      },
    ],
    ctaText: '查看更多評價',
  },
  seo: {
    title: '艾苜中醫診所',
    description: '艾苜中醫診所提供婦科、兒科、自律神經、針灸與中醫美容等調理服務。',
    ogTitle: '艾苜中醫診所',
    ogDescription: '以艾醫身，以苜養心。從預防到調理，守護您與家人的健康。',
    canonicalUrl: 'https://example.com/',
  },
}
