import {defineField, defineType} from 'sanity'

export const homePage = defineType({
  name: 'homePage',
  title: '首頁',
  type: 'document',
  groups: [
    {name: 'hero', title: '主視覺'},
    {name: 'about', title: '關於區塊'},
    {name: 'services', title: '主治項目'},
    {name: 'whyChoose', title: '為什麼選擇艾苜'},
    {name: 'team', title: '醫師陣容'},
    {name: 'process', title: '初診流程'},
    {name: 'booking', title: '預約區塊'},
    {name: 'faq', title: 'FAQ'},
    {name: 'gallery', title: '診所照片'},
    {name: 'testimonials', title: '真實見證'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'title', title: '文件名稱', type: 'string', initialValue: '首頁'}),
    defineField({
      name: 'hero',
      title: '主視覺',
      type: 'object',
      group: 'hero',
      fields: [
        defineField({name: 'titleLine1', title: '主標題第一行', type: 'string'}),
        defineField({name: 'titleLine2', title: '主標題第二行', type: 'string'}),
        defineField({name: 'subtitle', title: '副標題', type: 'text', rows: 3}),
        defineField({name: 'ctaText', title: 'CTA 文字', type: 'string'}),
        defineField({name: 'ctaTarget', title: 'CTA 目標', type: 'string'}),
        defineField({
          name: 'image',
          title: '圖片',
          type: 'image',
          options: {hotspot: true},
          fields: [defineField({name: 'alt', title: '替代文字', type: 'string'})],
        }),
      ],
    }),
    defineField({
      name: 'about',
      title: '關於區塊',
      type: 'object',
      group: 'about',
      fields: [
        defineField({name: 'title', title: '標題', type: 'string'}),
        defineField({name: 'englishTitle', title: '英文標題', type: 'string'}),
        defineField({name: 'lead', title: '引言', type: 'string'}),
        defineField({name: 'description', title: '說明', type: 'text', rows: 4}),
        defineField({name: 'features', title: '特色', type: 'array', of: [{type: 'aboutFeature'}]}),
        defineField({name: 'ctaText', title: 'CTA 文字', type: 'string'}),
        defineField({name: 'ctaTarget', title: 'CTA 目標', type: 'string'}),
        defineField({
          name: 'image',
          title: '圖片',
          type: 'image',
          options: {hotspot: true},
          fields: [defineField({name: 'alt', title: '替代文字', type: 'string'})],
        }),
      ],
    }),
    defineField({
      name: 'services',
      title: '主治項目',
      type: 'object',
      group: 'services',
      fields: [
        defineField({name: 'title', title: '標題', type: 'string'}),
        defineField({name: 'description', title: '說明', type: 'text', rows: 4}),
        defineField({
          name: 'serviceTreatmentRefs',
          title: '首頁要顯示的療程項目',
          description: '從全站療程項目選擇要顯示在首頁主治項目的最多 8 個項目。拖曳可調整順序；卡片名稱、icon、文案與連結由全站療程項目帶入。',
          type: 'array',
          of: [
            {
              type: 'reference',
              to: [{type: 'treatmentTaxonomyItem'}],
              weak: true,
              options: {
                filter: 'category in ["insurance", "featured"]',
                disableNew: true,
              },
            },
          ],
          validation: (Rule) => Rule.max(8).warning('首頁主治項目最多顯示 8 個。'),
        }),
        defineField({
          name: 'items',
          title: '項目（舊欄位）',
          description: '已改用「首頁要顯示的療程項目」管理。此欄位僅作舊資料 fallback。',
          type: 'array',
          of: [{type: 'serviceItem'}],
          readOnly: true,
          hidden: true,
          validation: (Rule) => Rule.max(8).warning('首頁主治項目最多顯示 8 個。'),
        }),
      ],
    }),
    defineField({
      name: 'whyChoose',
      title: '為什麼選擇艾苜',
      type: 'object',
      group: 'whyChoose',
      fields: [
        defineField({name: 'titleLine1', title: '標題第一行', type: 'string'}),
        defineField({name: 'titleLine2', title: '標題第二行', type: 'string'}),
        defineField({name: 'paragraphs', title: '段落', type: 'array', of: [{type: 'string'}]}),
        defineField({name: 'ctaText', title: 'CTA 文字', type: 'string'}),
        defineField({name: 'ctaTarget', title: 'CTA 目標', type: 'string'}),
        defineField({
          name: 'image',
          title: '圖片',
          type: 'image',
          options: {hotspot: true},
          fields: [defineField({name: 'alt', title: '替代文字', type: 'string'})],
        }),
      ],
    }),
    defineField({
      name: 'team',
      title: '醫師陣容',
      type: 'object',
      group: 'team',
      fields: [
        defineField({name: 'title', title: '標題', type: 'string'}),
        defineField({name: 'subtitle', title: '副標題', type: 'string'}),
        defineField({name: 'description', title: '說明', type: 'text', rows: 4}),
        defineField({name: 'doctors', title: '醫師清單', type: 'array', of: [{type: 'doctorSummary'}]}),
        defineField({
          name: 'image',
          title: '圖片',
          type: 'image',
          options: {hotspot: true},
          fields: [defineField({name: 'alt', title: '替代文字', type: 'string'})],
        }),
      ],
    }),
    defineField({
      name: 'process',
      title: '初診流程',
      type: 'object',
      group: 'process',
      fields: [
        defineField({name: 'title', title: '標題', type: 'string'}),
        defineField({name: 'subtitle', title: '副標題', type: 'string'}),
        defineField({name: 'steps', title: '步驟', type: 'array', of: [{type: 'processStep'}]}),
      ],
    }),
    defineField({
      name: 'booking',
      title: '預約區塊',
      type: 'object',
      group: 'booking',
      fields: [
        defineField({name: 'title', title: '標題', type: 'string'}),
        defineField({name: 'subtitle', title: '副標題', type: 'string'}),
        defineField({name: 'cards', title: '卡片', type: 'array', of: [{type: 'bookingCard'}]}),
      ],
    }),
    defineField({
      name: 'faq',
      title: 'FAQ',
      type: 'object',
      group: 'faq',
      fields: [
        defineField({name: 'titleLine1', title: '標題第一行', type: 'string'}),
        defineField({name: 'titleLine2', title: '標題第二行', type: 'string'}),
        defineField({name: 'description', title: '說明', type: 'text', rows: 3}),
        defineField({name: 'items', title: '問答項目', type: 'array', of: [{type: 'faqItem'}]}),
      ],
    }),
    defineField({
      name: 'gallery',
      title: '診所照片',
      type: 'object',
      group: 'gallery',
      fields: [
        defineField({name: 'images', title: '圖片', type: 'array', of: [{type: 'galleryImage'}]}),
      ],
    }),
    defineField({
      name: 'testimonials',
      title: '真實見證',
      type: 'object',
      group: 'testimonials',
      fields: [
        defineField({name: 'title', title: '標題', type: 'string'}),
        defineField({name: 'description', title: '說明', type: 'text', rows: 3}),
        defineField({name: 'items', title: '見證項目', type: 'array', of: [{type: 'testimonialItem'}]}),
        defineField({name: 'ctaText', title: 'CTA 文字', type: 'string'}),
      ],
    }),
    defineField({name: 'seo', title: 'SEO', type: 'seo', group: 'seo'}),
  ],
  preview: {
    select: {
      title: 'title',
    },
    prepare(selection) {
      return {
        title: selection.title || '首頁',
        subtitle: '單例文件',
      }
    },
  },
})
