import {defineField, defineType} from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: '全站設定',
  type: 'document',
  groups: [
    {name: 'header', title: '頁首', default: true},
    {name: 'footer', title: '頁尾'},
    {name: 'location', title: '診所據點'},
    {name: 'floating', title: '浮動按鈕'},
  ],
  fields: [
    defineField({name: 'title', title: '文件名稱', type: 'string', initialValue: '全站設定'}),
    defineField({
      name: 'headerLogo',
      title: 'Header Logo',
      type: 'image',
      group: 'header',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: '替代文字', type: 'string'})],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'headerNavItems',
      title: 'Header 導覽',
      type: 'array',
      group: 'header',
      of: [{type: 'siteNavItem'}],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'headerCta',
      title: 'Header 主要按鈕',
      type: 'siteLink',
      group: 'header',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'footerLogo',
      title: 'Footer Logo',
      type: 'image',
      group: 'footer',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: '替代文字', type: 'string'})],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'footerTagline',
      title: 'Footer 標語',
      type: 'string',
      group: 'footer',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'footerLinkGroups',
      title: 'Footer 連結群組',
      type: 'array',
      group: 'footer',
      of: [{type: 'footerLinkGroup'}],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'clinicInfoTitle',
      title: '診所資訊標題',
      type: 'string',
      group: 'footer',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'address',
      title: '地址',
      type: 'string',
      group: 'footer',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'phone',
      title: '電話',
      type: 'string',
      group: 'footer',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'email',
      title: '電子信箱',
      type: 'string',
      group: 'footer',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'socialLinks',
      title: '社群連結',
      type: 'array',
      group: 'footer',
      of: [{type: 'socialLink'}],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'locationSection',
      title: '診所據點區塊',
      type: 'object',
      group: 'location',
      fields: [
        defineField({
          name: 'title',
          title: '區塊標題',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'subtitle',
          title: '區塊副標',
          type: 'text',
          rows: 3,
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'clinicName',
          title: '診所名稱',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'clinicDescription',
          title: '診所描述',
          type: 'text',
          rows: 3,
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'hours',
          title: '營業時間',
          type: 'text',
          rows: 3,
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'mapLink',
          title: 'Google 地圖導航連結',
          type: 'url',
          validation: (Rule) => Rule.required().uri({allowRelative: false, scheme: ['http', 'https']}),
        }),
        defineField({
          name: 'mapEmbedUrl',
          title: 'Google 地圖嵌入連結',
          type: 'url',
          validation: (Rule) => Rule.required().uri({allowRelative: false, scheme: ['http', 'https']}),
        }),
        defineField({
          name: 'image',
          title: '區塊圖片',
          type: 'image',
          options: {hotspot: true},
          fields: [defineField({name: 'alt', title: '替代文字', type: 'string'})],
          validation: (Rule) => Rule.required(),
        }),
      ],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'copyright',
      title: '版權文字',
      type: 'string',
      group: 'footer',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'builderLink',
      title: '右下角連結',
      type: 'object',
      group: 'footer',
      fields: [
        defineField({
          name: 'label',
          title: '文字',
          type: 'string',
        }),
        defineField({
          name: 'kind',
          title: '連結類型',
          type: 'string',
          initialValue: 'external',
          options: {
            list: [
              {title: '頁面路由', value: 'route'},
              {title: '頁內區塊', value: 'scroll'},
              {title: '外部連結', value: 'external'},
            ],
            layout: 'radio',
          },
        }),
        defineField({
          name: 'target',
          title: '目標值',
          type: 'string',
          description: 'route 填 /about，scroll 填 booking，external 填完整網址',
        }),
      ],
    }),
    defineField({
      name: 'floatingLineButton',
      title: 'LINE 浮動按鈕',
      type: 'object',
      group: 'floating',
      fields: [
        defineField({
          name: 'enabled',
          title: '啟用按鈕',
          type: 'boolean',
          initialValue: true,
        }),
        defineField({
          name: 'ariaLabel',
          title: '按鈕描述',
          type: 'string',
          initialValue: 'Line客服',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'link',
          title: '按鈕連結',
          type: 'siteLink',
          validation: (Rule) => Rule.required(),
        }),
      ],
      validation: (Rule) => Rule.required(),
    }),
  ],
  preview: {
    select: {
      title: 'title',
      media: 'headerLogo',
    },
  },
})
